// Event and User types are now auto-generated by Prisma from prisma/schema.prisma.
// Import Event and User from '@/src/lib/dataFetching' wherever you need them.
// Only app-specific, non-database types live here.

// The allowed category values as a union type — "one of these exact strings".
// Used in forms, filters, and API validation.
export type Category =
  | 'musiikki'
  | 'liikunta'
  | 'taide'
  | 'teatteri'
  | 'sirkus'
  | 'luonto'
  | 'muu';
